name: Create release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Zip the repository folder
      - name: Zip folder
        run: |
          cd ${{ github.event.repository.name }}
          zip -r "${{ github.event.repository.name }}.zip" .
          mv "${{ github.event.repository.name }}.zip" ..
        shell: bash

      # Create a GitHub release
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.event.repository.name }}.zip
          tag_name: ${{ github.event.release.tag_name }}
          # Use release name if provided; otherwise, use the tag name as the title
          name: ${{ github.event.release.name }}
          body: ${{ github.event.release.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
